# This is a sample build configuration for Python in BitBucket.
image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - make test
